# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\87211\Desktop\DL_P\project_1\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1136, 797)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main2route = QtWidgets.QPushButton(self.centralwidget)
        self.main2route.setGeometry(QtCore.QRect(500, 220, 461, 121))
        self.main2route.setStyleSheet("font: 24pt \"霞鹜文楷\";")
        self.main2route.setObjectName("main2route")
        self.main2station = QtWidgets.QPushButton(self.centralwidget)
        self.main2station.setGeometry(QtCore.QRect(500, 380, 461, 121))
        self.main2station.setStyleSheet("font: 24pt \"霞鹜文楷\";")
        self.main2station.setObjectName("main2station")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(500, 540, 461, 121))
        self.exit_button.setStyleSheet("font: 24pt \"霞鹜文楷\";")
        self.exit_button.setObjectName("exit_button")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 361, 741))
        self.listView.setStyleSheet("background-image: url(\"C:background.jpg\")")
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 60, 431, 81))
        self.label.setStyleSheet("font: 28pt \"霞鹜文楷\";\n"
"text-decoration: underline;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(780, 150, 231, 41))
        self.label_2.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1136, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "合肥公交线路查询-主菜单"))
        self.main2route.setText(_translate("MainWindow", "查 找 线 路"))
        self.main2station.setText(_translate("MainWindow", "查 找 站 点"))
        self.exit_button.setText(_translate("MainWindow", "退 出"))
        self.label.setText(_translate("MainWindow", "合肥公交线路查询"))
        self.label_2.setText(_translate("MainWindow", "https://github.com/cxfann"))
